---
- name: Ensure haproxy is installed
  ansible.builtin.package:
    name: "{{ haproxy_package_name }}"
    state: present

- name: Create haproxy config file
  ansible.builtin.template:
    src: "etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    validate: haproxy -f %s -c -q
    owner: root
    group: root
    mode: 0644
  notify: Restart haproxy

- name: Ensure haproxy is enabled and started
  ansible.builtin.service:
    name: "{{ haproxy_service_name }}"
    state: started
    enabled: yes
